name: "Create file"

on: [workflow_dispatch]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ABURGELOID_BOT_APP_ID }}
          private_key: ${{ secrets.ABURGELOID_BOT_PRIVATE_KEY }}

      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/contents/{path}
          owner: aburgel
          repo: workflow_testing
          path: test.txt
          message: bot commit
          content: dGVzdGluZyAxMjM0Cg==
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
