name: Always fail

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Failure!"
          exit 1
